name: CI and CD 

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Install Karate
        uses: actions/download-artifact@v2
        with:
          name: karate
          path: karate.jar
        run: |
          java -jar karate.jar --configdir ./karate-config
      - name: Run Karate Tests
        run: java -jar karate.jar test
      - name: Run Test
        run: mvn test
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn sonar:sonar
      - name: Export test results as a tar file
        if: always()
        run: tar -cvf test-results.tar ./target/karate-reports/
      - name: Archieve test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.tar
      - name: Upload SonarQube Report
        uses: actions/upload-artifact@v3
        with:
          name: sonar-report
          path: target/sonar/report
      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run Node.js Tests
        run: npm test
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs